### ISSUE TITLE
Add address tracking

### ISSUE THREAD

**Issue by shifty11** [shifty11/cosmos-notifier#2]
- [x]  Feature to register and track an address for user
- [x]  New admin interface
    - [x]  Field to set trackable address
    - [x]  Field to set the time when alarm notification is triggered
    - [x]  Dropdown to select to which chat the alarm is sent
- [x]  DB migration
    - [x]  New table `AddressTracker` connected to `Chat` (Discord/Telegram), `Chain` and `ChainProposal`
- [x]  New alarm handler in chain_crawler
   - [x] Implement `SendVoteReminder`
- [x] Make it look nice on mobile
- [x] Make it look nice with dark mode
