### ISSUE TITLE
Tracker-improvements

### ISSUE THREAD

**Issue by shifty11** [shifty11/cosmos-notifier#6]
- [x] Use "reminder" instead of "tracker" in messge snackbar
- [x] Set text color of message snackbar to white
- [x] Set default for chat if there is no reminder
- [x] Change description 
   - [x] "Wallet address" instead of "Enter..."
   - [x] "Add your wallet address to get a reminder notification if you forget to vote on a proposal. You will get reminded before the vote ends."
- [x] Hide chat column if just one chat
- [x] Take out home button and use the logo instead
- [x] Make Menu text bigger and grey... bigger menu button?
- [x] Fix day/days in reminder message (hours/minutes)
